### ISSUE TITLE
Remove unused methods from Provider interface

### ISSUE THREAD

**Issue by manifest** [netology-group/account#13]
The only methods that are currently used:
- refreshAccessTokenRequest
- revokeRefreshTokenRequest
- accountRequest

These methods aren't used and may be changed in the future:
- accessTokenRequest
- linkRequest
- unlinkRequest
- authRequest
- isEnabledRequest
- enableRequest
- disableRequest
- removeAccountRequest

It would be better to remove them before the next major release, and adding new adjusted versions as we go.

**Comment by rogaldh** [comment]
The update was shipped.
