### ISSUE TITLE
Consider changing format of AccountId

### ISSUE THREAD

**Issue by manifest** [netology-group/account#5]
**AccountId** is composite type that consists from:
- **AccountLabel** is an internal tenant's account identifier that is unique within the specified audience
- **Audience** may represent oauth2 client id, or tenant id, or environment, etc.

Consider passing both to constructor of **Account**.

String representation is "{**accountLabel**}.{**audience**}".
For instance, accountLabel="12345" and audience="example.org" become "12345.example.org".

_Note that for requests to account's profile endpoint both **accountId** ("12345.example.org") and **accountLabel** ("12345") may make sense (for multi-audience providers and single-audience providers)_
_Note that it imply changing keys for objects in underlying storage (localStorage)._

**Comment by rogaldh** [comment]
The update was shipped.
