### ISSUE TITLE
Consider removing myAccountId property

### ISSUE THREAD

**Issue by manifest** [netology-group/account#7]
There is no reason to have [myAccountId](https://github.com/netology-group/account/blob/567ddc5297b639928aa8cf8896ee78d201c91f19/src/account.js#L18) property since we never update it. The value is a [constant](https://github.com/netology-group/account/blob/567ddc5297b639928aa8cf8896ee78d201c91f19/src/account.js#L4).

**Comment by rogaldh** [comment]
The update was shipped
